name: nanopack
channels:
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - arrow-cpp=21.0.0=hac1acdb_1
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - biopython=1.85=py313hb25bd0a_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py313haa0f9ac_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - chopper=0.12.0=hcdda2d0_0
  - clang=20.1.8=hfbc7b22_0
  - clang-20=20.1.8=default_h4fcecc7_0
  - expat=2.7.3=h3385a95_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-anaconda=1=h8fa9717_0
  - freetype=2.13.3=h4a9f257_0
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jansson=2.14=h5eee18b_1
  - kaleido-core=0.2.1=h7c8854e_0
  - kernel-headers_linux-64=4.18.0=h3108a97_1
  - ld_impl_linux-64=2.44=h153f514_2
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libclang-cpp20.1=20.1.8=default_h4fcecc7_0
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=15.2.0=hcb64138_107
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.71.0=h2d74bed_0
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libllvm20=20.1.8=h465586c_0
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.1=h697f920_0
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libthrift=0.22.0=hd8eb582_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mathjax=2.7.5=h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py313hacdc0fc_0
  - mkl_fft=2.1.1=py313h57662e1_0
  - mkl_random=1.3.0=py313h23c847b_0
  - nanoget=1.19.3=pyhdfd78af_0
  - nanoplot=1.46.1=pyhdfd78af_0
  - nanoqc=0.10.0=pyhdfd78af_0
  - narwhals=2.7.0=py313h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numexpr=2.14.1=py313h41d4191_0
  - numpy=2.3.5=py313h08c6c3d_0
  - numpy-base=2.3.5=py313h00548fb_0
  - openssl=3.0.18=hd6dcaed_0
  - orc=2.2.0=h372e9aa_0
  - packaging=25.0=py313h06a4308_1
  - pandas=2.3.3=py313h23c847b_1
  - pip=25.3=pyhc872135_0
  - plotly=6.3.0=py313h7040dfc_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=21.0.0=py313h23c847b_0
  - pysam=0.23.3=py313haee4d61_0
  - python=3.13.9=h7e8bc2b_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-kaleido=0.2.1=py313h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=3_cp313
  - pytz=2025.2=py313h06a4308_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - s2n=1.5.14=hdbd6064_0
  - scipy=1.16.3=py313h33bc11c_0
  - setuptools=80.9.0=py313h06a4308_0
  - six=1.17.0=py313h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.51.0=h2a70700_0
  - sysroot_linux-64=2.28=h3108a97_1
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - utf8proc=2.6.1=h5eee18b_1
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
prefix: /home/matevz2/miniconda3/envs/nanopack
